### ISSUE TITLE
Potential Syntax Issues?

### ISSUE THREAD

**Issue by ShaoVN** [Kiikuri/netgear_a6100_ac600_driver_installer_linux#1] opened 2023-05-08 04:54 UTC
After running this script my terminal responded with two errors.
Line 3: UID: readonly variable
and
Line 44: syntax error: unexpected end of file

All I did was download the zip, extract it, and ran:
sudo bash /<filepath>

**Comment by Kiikuri** [comment] 2023-05-08 10:13
Should be fixed now. 
It was caused by the if statement, where the script would force ```sudo su``` to run, in order to be able to do all of the required operations for installation. 
I'm not 100% sure that it works with just the ```sudo bash``` command, as I recall having some issues with that when I wrote the script. 
The safest bet is to run ```sudo su``` and then run the bash file. 
Alternatively, you can just use i.e. ```nano``` to fetch the executed commands from the file and run them manually to install the drivers.
I also updated the ReadMe to feature instructions for using the bash script.

**Closed as completed by Kiikuri** 2023-05-08 10:13 UTC
